# Import Libary and Data Loading

In [59]:
import pandas as pd
from scipy import stats

In [19]:
df=pd.read_csv('covid_19_indonesia_time_series_all.csv')

In [20]:
df

,Date,Location ISO Code,Location,New Cases,New Deaths,New Recovered,New Active Cases,Total Cases,Total Deaths,Total Recovered,...,Latitude,New Cases per Million,Total Cases per Million,New Deaths per Million,Total Deaths per Million,Total Deaths per 100rb,Case Fatality Rate,Case Recovered Rate,Growth Factor of New Cases,Growth Factor of New Deaths
0,3/1/2020,ID-JK,DKI Jakarta,2,0,0,2,39,20,41,...,-6.204699,0.18,3.60,0.00,1.84,0.18,51.28%,105.13%,NaN,NaN
1,3/2/2020,ID-JK,DKI Jakarta,2,0,0,2,41,20,41,...,-6.204699,0.18,3.78,0.00,1.84,0.18,48.78%,100.00%,1.00,1.0
2,3/2/2020,IDN,Indonesia,2,0,0,2,2,0,0,...,-0.789275,0.01,0.01,0.00,0.00,0.00,0.00%,0.00%,NaN,NaN
3,3/2/2020,ID-RI,Riau,1,0,0,1,2,0,3,...,0.511648,0.16,0.33,0.00,0.00,0.00,0.00%,150.00%,NaN,NaN
4,3/3/2020,ID-JK,DKI Jakarta,2,0,0,2,43,20,41,...,-6.204699,0.18,3.96,0.00,1.84,0.18,46.51%,95.35%,1.00,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21754,12/2/2021,ID-SA,Sulawesi Utara,2,0,0,2,34715,1056,33566,...,1.259638,0.76,13140.24,0.00,399.71,39.97,3.04%,96.69%,NaN,1.0
21755,12/2/2021,ID-SB,Sumatera Barat,4,0,0,4,89849,2152,87605,...,-0.850253,0.72,16279.22,0.00,389.91,38.99,2.40%,97.50%,4.00,1.0
21756,12/2/2021,ID-SS,Sumatera Selatan,4,0,0,4,59937,3071,56830,...,-3.216212,0.49,7293.78,0.00,373.71,37.37,5.12%,94.82%,4.00,1.0
21757,12/2/2021,ID-SU,Sumatera Utara,4,0,1,3,106045,2889,103061,...,2.191894,0.27,7129.13,0.00,194.22,19.42,2.72%,97.19%,1.00,1.0
21758,12/3/2021,IDN,Indonesia,245,8,328,-91,4257243,143858,4105680,...,-0.789275,0.92,16053.83,0.03,542.48,54.25,3.38%,96.44%,0.79,0.8

# Data Cleaning and prerprocessing

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21759 entries, 0 to 21758
Data columns (total 38 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Date                         21759 non-null  object
 1   Location ISO Code            21759 non-null  object
 2   Location                     21759 non-null  object
 3   New Cases                    21759 non-null  int64
 4   New Deaths                   21759 non-null  int64
 5   New Recovered                21759 non-null  int64
 6   New Active Cases             21759 non-null  int64
 7   Total Cases                  21759 non-null  int64
 8   Total Deaths                 21759 non-null  int64
 9   Total Recovered              21759 non-null  int64
 10  Total Active Cases           21759 non-null  int64
 11  Location Level               21759 non-null  object
 12  City or Regency              0 non-null      float64
 13  Province                     21117 non-null  object
 14  Country                      21759 non-null  object
 15  Continent                    21759 non-null  object
 16  Island                       21117 non-null  object
 17  Time Zone                    21117 non-null  object
 18  Special Status               3123 non-null   object
 19  Total Regencies              21759 non-null  int64
 20  Total Cities                 21145 non-null  float64
 21  Total Districts              21759 non-null  int64
 22  Total Urban Villages         21142 non-null  float64
 23  Total Rural Villages         21117 non-null  float64
 24  Area (km2)                   21759 non-null  int64
 25  Population                   21759 non-null  int64
 26  Population Density           21759 non-null  float64
 27  Longitude                    21759 non-null  float64
 28  Latitude                     21759 non-null  float64
 29  New Cases per Million        21759 non-null  float64
 30  Total Cases per Million      21759 non-null  float64
 31  New Deaths per Million       21759 non-null  float64
 32  Total Deaths per Million     21759 non-null  float64
 33  Total Deaths per 100rb       21759 non-null  float64
 34  Case Fatality Rate           21759 non-null  object
 35  Case Recovered Rate          21759 non-null  object
 36  Growth Factor of New Cases   20572 non-null  float64
 37  Growth Factor of New Deaths  19292 non-null  float64
dtypes: float64(14), int64(12), object(12)
memory usage: 6.3+ MB

In [22]:
df=df.astype({'Date':'datetime64[ns]'})

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21759 entries, 0 to 21758
Data columns (total 38 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Date                         21759 non-null  datetime64[ns]
 1   Location ISO Code            21759 non-null  object
 2   Location                     21759 non-null  object
 3   New Cases                    21759 non-null  int64
 4   New Deaths                   21759 non-null  int64
 5   New Recovered                21759 non-null  int64
 6   New Active Cases             21759 non-null  int64
 7   Total Cases                  21759 non-null  int64
 8   Total Deaths                 21759 non-null  int64
 9   Total Recovered              21759 non-null  int64
 10  Total Active Cases           21759 non-null  int64
 11  Location Level               21759 non-null  object
 12  City or Regency              0 non-null      float64
 13  Province                     21117 non-null  object
 14  Country                      21759 non-null  object
 15  Continent                    21759 non-null  object
 16  Island                       21117 non-null  object
 17  Time Zone                    21117 non-null  object
 18  Special Status               3123 non-null   object
 19  Total Regencies              21759 non-null  int64
 20  Total Cities                 21145 non-null  float64
 21  Total Districts              21759 non-null  int64
 22  Total Urban Villages         21142 non-null  float64
 23  Total Rural Villages         21117 non-null  float64
 24  Area (km2)                   21759 non-null  int64
 25  Population                   21759 non-null  int64
 26  Population Density           21759 non-null  float64
 27  Longitude                    21759 non-null  float64
 28  Latitude                     21759 non-null  float64
 29  New Cases per Million        21759 non-null  float64
 30  Total Cases per Million      21759 non-null  float64
 31  New Deaths per Million       21759 non-null  float64
 32  Total Deaths per Million     21759 non-null  float64
 33  Total Deaths per 100rb       21759 non-null  float64
 34  Case Fatality Rate           21759 non-null  object
 35  Case Recovered Rate          21759 non-null  object
 36  Growth Factor of New Cases   20572 non-null  float64
 37  Growth Factor of New Deaths  19292 non-null  float64
dtypes: datetime64[ns](1), float64(14), int64(12), object(11)
memory usage: 6.3+ MB

In [24]:
df.isna().sum()

Date                               0
Location ISO Code                  0
Location                           0
New Cases                          0
New Deaths                         0
New Recovered                      0
New Active Cases                   0
Total Cases                        0
Total Deaths                       0
Total Recovered                    0
Total Active Cases                 0
Location Level                     0
City or Regency                21759
Province                         642
Country                            0
Continent                          0
Island                           642
Time Zone                        642
Special Status                 18636
Total Regencies                    0
Total Cities                     614
Total Districts                    0
Total Urban Villages             617
Total Rural Villages             642
Area (km2)                         0
Population                         0
Population Density                 0
Longitude                          0
Latitude                           0
New Cases per Million              0
Total Cases per Million            0
New Deaths per Million             0
Total Deaths per Million           0
Total Deaths per 100rb             0
Case Fatality Rate                 0
Case Recovered Rate                0
Growth Factor of New Cases      1187
Growth Factor of New Deaths     2467
dtype: int64

In [25]:
df.columns

Index(['Date', 'Location ISO Code', 'Location', 'New Cases', 'New Deaths',
       'New Recovered', 'New Active Cases', 'Total Cases', 'Total Deaths',
       'Total Recovered', 'Total Active Cases', 'Location Level',
       'City or Regency', 'Province', 'Country', 'Continent', 'Island',
       'Time Zone', 'Special Status', 'Total Regencies', 'Total Cities',
       'Total Districts', 'Total Urban Villages', 'Total Rural Villages',
       'Area (km2)', 'Population', 'Population Density', 'Longitude',
       'Latitude', 'New Cases per Million', 'Total Cases per Million',
       'New Deaths per Million', 'Total Deaths per Million',
       'Total Deaths per 100rb', 'Case Fatality Rate', 'Case Recovered Rate',
       'Growth Factor of New Cases', 'Growth Factor of New Deaths'],
      dtype='object')

In [26]:
dfc=df.copy().drop(columns=['Special Status','City or Regency'])

In [27]:
dfc=dfc.dropna()

In [28]:
dfc

,Date,Location ISO Code,Location,New Cases,New Deaths,New Recovered,New Active Cases,Total Cases,Total Deaths,Total Recovered,...,Latitude,New Cases per Million,Total Cases per Million,New Deaths per Million,Total Deaths per Million,Total Deaths per 100rb,Case Fatality Rate,Case Recovered Rate,Growth Factor of New Cases,Growth Factor of New Deaths
7,2020-03-03,ID-RI,Riau,0,0,0,0,2,0,3,...,0.511648,0.00,0.33,0.0,0.00,0.00,0.00%,150.00%,0.0,1.0
10,2020-03-04,ID-JB,Jawa Barat,1,0,0,1,2,1,8,...,-6.920432,0.02,0.04,0.0,0.02,0.00,50.00%,400.00%,1.0,0.0
11,2020-03-04,ID-RI,Riau,0,0,0,0,2,0,3,...,0.511648,0.00,0.33,0.0,0.00,0.00,0.00%,150.00%,1.0,1.0
14,2020-03-05,ID-JB,Jawa Barat,1,0,0,1,3,1,8,...,-6.920432,0.02,0.07,0.0,0.02,0.00,33.33%,266.67%,1.0,1.0
15,2020-03-05,ID-RI,Riau,0,0,0,0,2,0,3,...,0.511648,0.00,0.33,0.0,0.00,0.00,0.00%,150.00%,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21750,2021-12-02,ID-RI,Riau,4,0,0,4,128825,4109,124123,...,0.511648,0.66,21208.90,0.0,676.48,67.65,3.19%,96.35%,0.5,1.0
21752,2021-12-02,ID-ST,Sulawesi Tengah,11,0,2,9,47153,1602,45503,...,-1.004137,3.72,15953.96,0.0,542.03,54.20,3.40%,96.50%,2.2,1.0
21755,2021-12-02,ID-SB,Sumatera Barat,4,0,0,4,89849,2152,87605,...,-0.850253,0.72,16279.22,0.0,389.91,38.99,2.40%,97.50%,4.0,1.0
21756,2021-12-02,ID-SS,Sumatera Selatan,4,0,0,4,59937,3071,56830,...,-3.216212,0.49,7293.78,0.0,373.71,37.37,5.12%,94.82%,4.0,1.0
21757,2021-12-02,ID-SU,Sumatera Utara,4,0,1,3,106045,2889,103061,...,2.191894,0.27,7129.13,0.0,194.22,19.42,2.72%,97.19%,1.0,1.0

# Hypothesis Testing

In [29]:
dfc.columns

Index(['Date', 'Location ISO Code', 'Location', 'New Cases', 'New Deaths',
       'New Recovered', 'New Active Cases', 'Total Cases', 'Total Deaths',
       'Total Recovered', 'Total Active Cases', 'Location Level', 'Province',
       'Country', 'Continent', 'Island', 'Time Zone', 'Total Regencies',
       'Total Cities', 'Total Districts', 'Total Urban Villages',
       'Total Rural Villages', 'Area (km2)', 'Population',
       'Population Density', 'Longitude', 'Latitude', 'New Cases per Million',
       'Total Cases per Million', 'New Deaths per Million',
       'Total Deaths per Million', 'Total Deaths per 100rb',
       'Case Fatality Rate', 'Case Recovered Rate',
       'Growth Factor of New Cases', 'Growth Factor of New Deaths'],
      dtype='object')

In [30]:
dfc

,Date,Location ISO Code,Location,New Cases,New Deaths,New Recovered,New Active Cases,Total Cases,Total Deaths,Total Recovered,...,Latitude,New Cases per Million,Total Cases per Million,New Deaths per Million,Total Deaths per Million,Total Deaths per 100rb,Case Fatality Rate,Case Recovered Rate,Growth Factor of New Cases,Growth Factor of New Deaths
7,2020-03-03,ID-RI,Riau,0,0,0,0,2,0,3,...,0.511648,0.00,0.33,0.0,0.00,0.00,0.00%,150.00%,0.0,1.0
10,2020-03-04,ID-JB,Jawa Barat,1,0,0,1,2,1,8,...,-6.920432,0.02,0.04,0.0,0.02,0.00,50.00%,400.00%,1.0,0.0
11,2020-03-04,ID-RI,Riau,0,0,0,0,2,0,3,...,0.511648,0.00,0.33,0.0,0.00,0.00,0.00%,150.00%,1.0,1.0
14,2020-03-05,ID-JB,Jawa Barat,1,0,0,1,3,1,8,...,-6.920432,0.02,0.07,0.0,0.02,0.00,33.33%,266.67%,1.0,1.0
15,2020-03-05,ID-RI,Riau,0,0,0,0,2,0,3,...,0.511648,0.00,0.33,0.0,0.00,0.00,0.00%,150.00%,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21750,2021-12-02,ID-RI,Riau,4,0,0,4,128825,4109,124123,...,0.511648,0.66,21208.90,0.0,676.48,67.65,3.19%,96.35%,0.5,1.0
21752,2021-12-02,ID-ST,Sulawesi Tengah,11,0,2,9,47153,1602,45503,...,-1.004137,3.72,15953.96,0.0,542.03,54.20,3.40%,96.50%,2.2,1.0
21755,2021-12-02,ID-SB,Sumatera Barat,4,0,0,4,89849,2152,87605,...,-0.850253,0.72,16279.22,0.0,389.91,38.99,2.40%,97.50%,4.0,1.0
21756,2021-12-02,ID-SS,Sumatera Selatan,4,0,0,4,59937,3071,56830,...,-3.216212,0.49,7293.78,0.0,373.71,37.37,5.12%,94.82%,4.0,1.0
21757,2021-12-02,ID-SU,Sumatera Utara,4,0,1,3,106045,2889,103061,...,2.191894,0.27,7129.13,0.0,194.22,19.42,2.72%,97.19%,1.0,1.0

In [68]:
df2020=dfc[dfc['Date'].dt.year==2020]
df2021=dfc[dfc['Date'].dt.year!=2020]

df2020nc=df2020['New Cases']
df2021nc=df2021['New Cases']

In [69]:
df2020nc

7          0
10         1
11         0
14         1
15         0
        ...
10013     38
10014     87
10015    117
10016     92
10017     83
Name: New Cases, Length: 7024, dtype: int64

In [70]:
df2021nc

10019    101
10020    287
10021     68
10024     25
10026     36
        ...
21750      4
21752     11
21755      4
21756      4
21757      4
Name: New Cases, Length: 9027, dtype: int64

Assumption : New Cases on 2021 is lower than new cases in 2020 --> Sample vs Sample Dependent (two paired test)

- H0 = Mean 2021 Covid New Cases is less than or equeal to than the mean of 2020 Covid New Cases
- H1 = Mean 2021 Covid New Cases is higher than the mean of 2020 Covid New Cases
- Critical Value is 0,05

In [71]:
df2020mean = df2020nc.mean()
df2021mean = df2021nc.mean()

In [72]:
print(df2020mean)
print(df2021mean)

71.42155466970387
300.63498393707766

In [75]:
t_stat,p_val = stats.ttest_rel(df2020nc.sample(7000),df2021nc.sample(7000)) #we take 40000 sample of each data to make the size the same.
print('P-value:',p_val)

P-value: 2.5690490936203e-136

- The P Value is above significant value, hence we accept H0
- So the conclusion is the mean of new covid cases on 2021 is